"""Add chart_insights table for on-demand insights

Revision ID: acb519f26bbe
Revises: 3fbe19e756e4
Create Date: 2025-11-19 11:34:18.319646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acb519f26bbe'
down_revision: Union[str, Sequence[str], None] = '3fbe19e756e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('chart_hash', sa.String(length=64), nullable=False),
    sa.Column('chart_type', sa.String(length=20), nullable=False),
    sa.Column('chart_title', sa.String(length=255), nullable=False),
    sa.Column('insight', sa.Text(), nullable=False),
    sa.Column('insight_type', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chart_insights_chart_hash'), 'chart_insights', ['chart_hash'], unique=False)
    op.create_index(op.f('ix_chart_insights_id'), 'chart_insights', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chart_insights_id'), table_name='chart_insights')
    op.drop_index(op.f('ix_chart_insights_chart_hash'), table_name='chart_insights')
    op.drop_table('chart_insights')
    # ### end Alembic commands ###
