"""add_file_analyses_table

Revision ID: bb3e5a3d2e96
Revises: acb519f26bbe
Create Date: 2025-11-19 13:51:38.138277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb3e5a3d2e96'
down_revision: Union[str, Sequence[str], None] = 'acb519f26bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('analysis_json', sa.Text(), nullable=False),
    sa.Column('user_intent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_analyses_id'), 'file_analyses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_analyses_id'), table_name='file_analyses')
    op.drop_table('file_analyses')
    # ### end Alembic commands ###
